config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "product_details#index"
  resources :product_details
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product_detail.rb
class ProductDetail < ApplicationRecord
	
	validates :name, :price, :description, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/product_details_controller.rb
class ProductDetailsController < ApplicationController

	before_action :set_product, only: [:edit, :update, :show, :destroy] 

	def index
		@product = ProductDetail.all
	end

	def new
		@product = ProductDetail.new
	end

	def create
		@product = ProductDetail.new(product_params)
		if @product.save
			redirect_to product_details_path
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @product.update(product_params)
			redirect_to product_details_path
		else
			render :new
		end
	end

	def show 
	end

	def destroy
		if @product.destroy
			redirect_to product_details_path
		end
	end

	private

	def product_params
		params.require(:product_detail).permit(:name, :price, :description)
	end

	def set_product
		@product = ProductDetail.find_by(params[:id])
		rescue ActiveRecord::RecordNotFound => error
			redirect_to product_details_path, notic: error 	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_details_helper.rb
module ProductDetailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
  </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/product_details/_form.html.erb
	<%= form_with model:@product do |form|%>

		<div class="row">
			<div class="col-lg-6">
				<div class="form-group">
					<%= form.label :Name, class:"mb-2" %>
					<%= form.text_field :name, class:"form-control-lg form-control"%>
					<% @product.errors.full_messages_for(:name).each do |message| %>
						<p class="text-danger"><%= message %></p>
					<% end %>
				</div>
			</div>

			<div class="col-lg-6">
				<div class="form-group">
					<%= form.label :Price, class:"mb-2" %>
					<%= form.text_field :price, class:"form-control form-control-lg" %>
					<% @product.errors.full_messages_for(:price).each do |message| %>
						<p class="text-danger"><%= message %></p>
					<% end %>
				</div>
			</div>
		</div><br><br>

		<div class="row">
			<div class="col-lg-6">
				<div class="form-group">
					<%= form.label :description, class:"mb-2" %>
					<%= form.text_field :description, class:"form-control form-control-lg"%>
					<% @product.errors.full_messages_for(:description).each do |message| %>
						<p class="text-danger"><%= message %></p>
					<% end %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-12">
				<div class="form-group">
					<%= form.submit class:"btn btn-primary btn-lg mt-5" %>
					<%= link_to "Back to Product", product_details_path, class:"btn btn-outline-primary btn-lg mt-5" %>
				</div>
			</div>
		</div>

	<% end %>

app/views/product_details/edit.html.erb
<div class="col-lg-12">
	<div class="card mt-5 mb-5">
		<div class="card-body">
			<h1 class="text-center"> Edit Product </h1>
		</div>
	</div>

	<%= render 'form' %>

</div>

app/views/product_details/index.html.erb
<div class="col-lg-12">
	<div class="card mt-5 mb-5">
		<div class="card-body">
			<h1 class="text-center">Product Listing</h1>
		</div>
	</div>

	<%= link_to "Create Product", new_product_detail_path, class:"btn btn-primary btn-lg rounded-0" %>
	<table class="table table-boarder">
		<thead>
			<tr>
				<th>Name</th>
				<th>Price</th>
				<th>Description</th>
				<th>Action</th>

			</tr>
		</thead>

		<tbody>
			<% @product.each do |product|%>
			<tr>
				<td><%= product.name %></td>
				<td><%= product.price %></td>
				<td><%= product.description %></td>
				<td><%= link_to "Edit", edit_product_detail_path(product), class:"btn btn-primary " %>
					<%= link_to "view", product_detail_path(product), class:"btn btn-primary" %>
					<%= link_to "Delete", product_detail_path(product), class:"btn btn-danger", method: :delete, data: {confirm:"Are You sure to delete product"} %>
				</td>
			</tr>
			<% end %>

		</tbody>
	</table>
</div>

app/views/product_details/new.html.erb
<div class="col-lg-12">
	<div class="card mt-5 mb-5">
		<div class="card-body">
			<h1 class="text-center"> Create New Product </h1>
		</div>
	</div>

<%= render 'form' %>

</div>

app/views/product_details/show.html.erb
<div class="col-lg-12">
	<div class="card mt-5 mb-5">
		<div class="card-body">
			<h1 class="text-center"> Show Product </h1>
			<div class="row mt-3 mb-3">
				<div col-lg-6>
					<p class="lead"><strong>Name:</strong><%= @product.name %></p>
				</div>
			</div>

			<div class="row mt-3 mb-3">
				<div col-lg-6>
					<p class="lead"><strong>Price:</strong><%= @product.price %></p>
				</div>
			</div>

			<div class="row mt-3 mb-3">
				<div col-lg-6>
					<p class="lead"><strong>Description:</strong><%= @product.description %></p>
				</div>
			</div>

			<%= link_to "Edit", edit_product_detail_path(@product), class:"btn btn-primary btn-lg"%>
			<%= link_to "Back to Product", product_details_path, class:"btn btn-outline-primary btn-lg" %>

		</div>
	</div>



</div>